import os

import pytest

from config import ROOT
from src.Saver import JSONSaver
from src.Vacancy import Vacancy


@pytest.fixture
def item_for_test():
    vacancy_path = os.path.join(ROOT, 'tests', 'data_for_test.json')
    json_saver = JSONSaver(vacancy_path)
    loaded_vacancies = json_saver.get_vacancy(vacancy_path)
    return loaded_vacancies


def test_sort_salary(item_for_test):
    """Проверка работы метода sort_salary."""
    assert Vacancy.sort_salary(item_for_test, '90000') == [{'id': '92088186', 'premium': False, 'name': 'Junior BackEnd Developer', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 90000, 'to': 130000, 'currency': 'RUR', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-02-19T16:02:08+0300', 'created_at': '2024-02-19T16:02:08+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=92088186', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/92088186?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/92088186', 'relations': [], 'employer': {'id': '3471807', 'name': 'ЭС-АЙ Безопасность', 'url': 'https://api.hh.ru/employers/3471807', 'alternate_url': 'https://hh.ru/employer/3471807', 'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/2602385.jpeg', '240': 'https://hhcdn.ru/employer-logo/2602386.jpeg', 'original': 'https://hhcdn.ru/employer-logo-original/540228.jpg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3471807', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Успешное участие в олимпиадах по программированию. Математическая подготовка: численные методы, линейная алгебра, статистика, методы оптимизации. Знание PHP.', 'responsibility': 'Реализация нового функционала платформы. Разработка и поддержка существующего API. Оптимизация работы системы, поиск и устранение узких мест.'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]


def test_sort_currency(item_for_test):
    """Проверка работы метода sort_currency."""
    assert Vacancy.sort_currency(Vacancy.sort_salary(item_for_test, '90000')) == [{'id': '92088186', 'premium': False, 'name': 'Junior BackEnd Developer', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 90000, 'to': 130000, 'currency': 'руб.', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-02-19T16:02:08+0300', 'created_at': '2024-02-19T16:02:08+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=92088186', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/92088186?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/92088186', 'relations': [], 'employer': {'id': '3471807', 'name': 'ЭС-АЙ Безопасность', 'url': 'https://api.hh.ru/employers/3471807', 'alternate_url': 'https://hh.ru/employer/3471807', 'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/2602385.jpeg', '240': 'https://hhcdn.ru/employer-logo/2602386.jpeg', 'original': 'https://hhcdn.ru/employer-logo-original/540228.jpg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3471807', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Успешное участие в олимпиадах по программированию. Математическая подготовка: численные методы, линейная алгебра, статистика, методы оптимизации. Знание PHP.', 'responsibility': 'Реализация нового функционала платформы. Разработка и поддержка существующего API. Оптимизация работы системы, поиск и устранение узких мест.'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]


def test_sort_req_res(item_for_test):
    """Проверка работы метода sort_req_res."""
    assert Vacancy.sort_req_res(Vacancy.sort_currency(Vacancy.sort_salary(item_for_test, '90000'))) == [{'id': '92088186', 'premium': False, 'name': 'Junior BackEnd Developer', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 90000, 'to': 130000, 'currency': 'руб.', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-02-19T16:02:08+0300', 'created_at': '2024-02-19T16:02:08+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=92088186', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/92088186?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/92088186', 'relations': [], 'employer': {'id': '3471807', 'name': 'ЭС-АЙ Безопасность', 'url': 'https://api.hh.ru/employers/3471807', 'alternate_url': 'https://hh.ru/employer/3471807', 'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/2602385.jpeg', '240': 'https://hhcdn.ru/employer-logo/2602386.jpeg', 'original': 'https://hhcdn.ru/employer-logo-original/540228.jpg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3471807', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Успешное участие в олимпиадах по программированию. Математическая подготовка: численные методы, линейная алгебра, статистика, методы оптимизации. Знание PHP.', 'responsibility': 'Реализация нового функционала платформы. Разработка и поддержка существующего API. Оптимизация работы системы, поиск и устранение узких мест.'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]


def test_sort_area(item_for_test):
    """Проверка работы метода sort_area."""
    assert Vacancy.sort_area(Vacancy.sort_req_res(Vacancy.sort_currency(Vacancy.sort_salary(item_for_test, '90000'))), 'Москва') == [{'id': '92088186', 'premium': False, 'name': 'Junior BackEnd Developer', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 90000, 'to': 130000, 'currency': 'руб.', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-02-19T16:02:08+0300', 'created_at': '2024-02-19T16:02:08+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=92088186', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/92088186?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/92088186', 'relations': [], 'employer': {'id': '3471807', 'name': 'ЭС-АЙ Безопасность', 'url': 'https://api.hh.ru/employers/3471807', 'alternate_url': 'https://hh.ru/employer/3471807', 'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/2602385.jpeg', '240': 'https://hhcdn.ru/employer-logo/2602386.jpeg', 'original': 'https://hhcdn.ru/employer-logo-original/540228.jpg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3471807', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Успешное участие в олимпиадах по программированию. Математическая подготовка: численные методы, линейная алгебра, статистика, методы оптимизации. Знание PHP.', 'responsibility': 'Реализация нового функционала платформы. Разработка и поддержка существующего API. Оптимизация работы системы, поиск и устранение узких мест.'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]


def test_cast_to_object_list():
    """Проверка работы метода cast_to_object_list."""
    assert Vacancy.cast_to_object_list([{'id': '92088186', 'premium': False, 'name': 'Junior BackEnd Developer', 'department': None, 'has_test': False, 'response_letter_required': False, 'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'}, 'salary': {'from': 90000, 'to': 130000, 'currency': 'руб.', 'gross': False}, 'type': {'id': 'open', 'name': 'Открытая'}, 'address': None, 'response_url': None, 'sort_point_distance': None, 'published_at': '2024-02-19T16:02:08+0300', 'created_at': '2024-02-19T16:02:08+0300', 'archived': False, 'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=92088186', 'show_logo_in_search': None, 'insider_interview': None, 'url': 'https://api.hh.ru/vacancies/92088186?host=hh.ru', 'alternate_url': 'https://hh.ru/vacancy/92088186', 'relations': [], 'employer': {'id': '3471807', 'name': 'ЭС-АЙ Безопасность', 'url': 'https://api.hh.ru/employers/3471807', 'alternate_url': 'https://hh.ru/employer/3471807', 'logo_urls': {'90': 'https://hhcdn.ru/employer-logo/2602385.jpeg', '240': 'https://hhcdn.ru/employer-logo/2602386.jpeg', 'original': 'https://hhcdn.ru/employer-logo-original/540228.jpg'}, 'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=3471807', 'accredited_it_employer': False, 'trusted': True}, 'snippet': {'requirement': 'Успешное участие в олимпиадах по программированию. Математическая подготовка: численные методы, линейная алгебра, статистика, методы оптимизации. Знание PHP.', 'responsibility': 'Реализация нового функционала платформы. Разработка и поддержка существующего API. Оптимизация работы системы, поиск и устранение узких мест.'}, 'contacts': None, 'schedule': {'id': 'fullDay', 'name': 'Полный день'}, 'working_days': [], 'working_time_intervals': [], 'working_time_modes': [], 'accept_temporary': False, 'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}], 'accept_incomplete_resumes': False, 'experience': {'id': 'between1And3', 'name': 'От 1 года до 3 лет'}, 'employment': {'id': 'full', 'name': 'Полная занятость'}, 'adv_response_url': None, 'is_adv_vacancy': False, 'adv_context': None}]) is None


def test_print_vacancies():
    """Проверка работы метода print_vacancies."""
    vacancies = Vacancy.vacancies_list
    assert Vacancy.print_vacancies(vacancies) is None
